### ISSUE TITLE
Dependency missing: sncrypto-web

### ISSUE THREAD

**Issue by B1773rm4n** [standardnotes/decrypt#20]
The source of
https://github.com/standardnotes/decrypt/blob/master/package.json
mentions 2 dependencies:

    "@standardnotes/sncrypto-web": "^1.2.9",
    "@standardnotes/snjs": "^2.3.0"

Seemingly sncrypto-web should be existing here on Github but it doesn't seem to exist.

**Comment by moughxyz** [comment]
SNCrypto has moved here: https://github.com/standardnotes/snjs/tree/master/packages

`decrypt` will also be moving there.
