### ISSUE TITLE
Tag the repo

### ISSUE THREAD

**Issue by proletarius101** [standardnotes/decrypt#6]
npm modules is meant to be tagged if it specifies a version and is hosted on git. Otherwise, it won't be able to be access via [git-dep](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#git-urls-as-dependencies). Another result you can't cache this and load this module offline bacause only the github-dependency mode can tolerate this combination

**Comment by baptiste-grob** [comment]
Hey @proletarius101, we use the `#<commit-ish>` format to access specific versions of this package and it's worked well for us since the repo is not published on npm 🙂 Could you clarify what the issue is with that approach?

**Comment by proletarius101** [comment]
Hmmm, I can't really remember. Given that the standardnotes flatpak works fine, let's just close this for now.
